# generated by datamodel-codegen:
#   filename:  person.json
#   timestamp: 2026-06-19T00:42:13+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class Pet(BaseModel):
    name: str | None = None
    age: int | None = None


class Person(BaseModel):
    first_name: str = Field(..., description="The person's first name.")
    last_name: str = Field(..., description="The person's last name.")
    age: conint(ge=0) | None = Field(None, description='Age in years.')
    pets: list[Pet] | None = None
    comment: None = Field(None)
