# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-19T00:42:12+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Id(BaseModel):
    type: str


class Name(BaseModel):
    type: str


class Email(BaseModel):
    type: str


class Properties(BaseModel):
    id: Id
    name: Name
    email: Email


class User(BaseModel):
    type: str
    required: list[str]
    properties: Properties


class Schemas(BaseModel):
    User_1: User = Field(..., alias='User')


class Components(BaseModel):
    schemas: Schemas


class Model(BaseModel):
    components: Components
