# generated by datamodel-codegen:
#   filename:  users.csv
#   timestamp: 2026-06-19T00:42:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    name: str
    age: str
    email: str
